# Generated by Django 5.1.3 on 2024-11-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="programmers_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
