# Generated by Django 5.1.3 on 2024-11-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_programmers_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="programmers_password",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
