# Generated by Django 5.1.3 on 2024-11-11 07:42

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_programmers_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='programmers_password',
            field=users.models.EncryptedCharField(max_length=255, null=True),
        ),
    ]
