# Generated by Django 5.1.3 on 2024-11-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_programmers_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="initial_github_commit_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="initial_github_commits",
            field=models.IntegerField(default=0),
        ),
    ]
