# Generated by Django 5.1.3 on 2024-12-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user_followers_count_user_following_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_level",
        ),
        migrations.AddField(
            model_name="user",
            name="user_tier",
            field=models.CharField(default="Bronze5", max_length=25),
        ),
    ]
