# Generated by Django 5.1.3 on 2024-11-25 13:32

import items.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=items.models.item_image_upload_to
            ),
        ),
    ]
