# Generated by Django 5.1.3 on 2024-12-28 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TILs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TILImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('image', models.URLField(max_length=500)),
                ('is_temporary', models.BooleanField(default=True)),
                ('til', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='TILs.til')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
