# Generated by Django 5.1.3 on 2025-01-01 15:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("TILs", "0002_tilimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tilimage",
            old_name="til",
            new_name="TIL",
        ),
    ]
