# Generated by Django 5.1.3 on 2024-11-16 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baekjoons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baekjoon',
            old_name='solved_problem',
            new_name='solved',
        ),
    ]
