# Generated by Django 5.1.3 on 2024-11-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coins',
            field=models.IntegerField(),
        ),
    ]
