# Generated by Django 5.1.3 on 2024-11-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0002_alter_coin_coins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coin",
            name="verb",
            field=models.CharField(
                choices=[
                    ("attendance", "출석"),
                    ("github", "깃허브 커밋"),
                    ("baekjoon", "백준 문제 풀이"),
                    ("programmers", "프로그래머스 문제 풀이"),
                    ("challenge", "챌린지 성공"),
                    ("purchase", "아이템 구매"),
                ],
                max_length=255,
            ),
        ),
    ]
