# Generated by Django 5.1.3 on 2025-01-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0003_alter_coin_verb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coin",
            name="verb",
            field=models.CharField(
                choices=[
                    ("attendance", "출석"),
                    ("github", "깃허브 커밋"),
                    ("baekjoon", "백준 문제 풀이"),
                    ("programmers", "프로그래머스 문제 풀이"),
                    ("challenge_bet", "챌린지 베팅"),
                    ("challenge_reward", "챌린지 보상"),
                    ("purchase", "아이템 구매"),
                ],
                max_length=255,
            ),
        ),
    ]
