# Generated by Django 5.1.3 on 2025-01-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("github_commits", "GitHub Commits"),
                            ("problem_solving", "Problem Solving"),
                        ],
                        max_length=20,
                        verbose_name="Competition Condition",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Start Date")),
                ("end_date", models.DateTimeField(verbose_name="End Date")),
                (
                    "term",
                    models.BooleanField(
                        help_text="True: Short-term (1-12 hours), False: Long-term (1 day+)",
                        verbose_name="Term Duration",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="ongoing",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "total_bet_coins",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Bet Coins"
                    ),
                ),
                (
                    "reward_coins",
                    models.PositiveIntegerField(default=0, verbose_name="Reward Coins"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
        ),
    ]
