# Generated by Django 5.1.3 on 2025-01-06 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0002_alter_challenge_condition_alter_challenge_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="term",
        ),
        migrations.AddField(
            model_name="challenge",
            name="duration",
            field=models.IntegerField(
                choices=[(3, "3일"), (7, "7일"), (30, "30일")],
                default=7,
                verbose_name="Challenge Duration",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="participants",
            field=models.ManyToManyField(
                related_name="challenges", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_challenges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="start_date",
            field=models.DateField(verbose_name="Start Date"),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "PENDING"),
                    ("ongoing", "ONGOING"),
                    ("completed", "COMPLETED"),
                    ("rejected", "REJECTED"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
